# Site settings
title: My digital garden 
header-img: img/home-bg.png
email: kathyvng@gmail.com
copyright_name: Kathyvng
description: > # this means to ignore newlines until "baseurl:"
  Business+Tech+Web development+Information systems
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Kathyvng
learn_profile: Kathyvng
email_username: kathyvng@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
